In [1]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method


In [2]:
l =[1,2,3]

In [3]:
l.append?

Docstring: L.append(object) -> None -- append object to end
Type:      builtin_function_or_method


In [4]:
l?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
list() -> new empty list
list(iterable) -> new list initialized from iterable's items


In [5]:
def square(x):
    """test doc"""
    return x*x

In [6]:
square?

Signature: square(x)
Docstring: test doc
File:      c:\users\kapmik\ipython\ipynb\pythondatasciencehandbook-master\exercise\<ipython-input-5-e5d4fdd00fb7>
Type:      function


In [7]:
square??


Signature: square(x)
Source:   
def square(x):
    """test doc"""
    return x*x
File:      c:\users\kapmik\ipython\ipynb\pythondatasciencehandbook-master\exercise\<ipython-input-5-e5d4fdd00fb7>
Type:      function


In [8]:
l??

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
list() -> new empty list
list(iterable) -> new list initialized from iterable's items


In [11]:
%%timeit  
L = [n**2 for n in range(1000)]

1.1 ms ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
!pwd

"pwd" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.


In [13]:
import numpy

In [15]:
numpy.__version__

'1.14.3'

In [17]:
import numpy as np

In [19]:
 np.array([1,2,3])

array([1, 2, 3])

In [21]:
 np.array([1,2.,3])

array([1., 2., 3.])

In [24]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.full((3,5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])