In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
np.unique([1,2,5,6,6], return_counts=True)

(array([1, 2, 5, 6]), array([1, 1, 1, 2], dtype=int64))

In [4]:
np.unique([[1,2,5,6,6], [1,2,5,2,6]], return_counts=True, axis=1)

(array([[1, 2, 5, 6, 6],
        [1, 2, 5, 2, 6]]), array([1, 1, 1, 1, 1], dtype=int64))

In [5]:
np.apply_along_axis(np.bincount, axis=1, arr=[[1,2,5,6,6], [1,2,5,2,6]])

array([[0, 1, 1, 0, 0, 1, 2],
       [0, 1, 2, 0, 0, 1, 1]], dtype=int64)

In [6]:
np.where(np.array([[1,2],[3,4]])>np.array([[2],[4]]))

(array([], dtype=int64), array([], dtype=int64))

In [7]:
np.array([[4,3],[3,5]])>np.array([[2],[4]])

array([[ True,  True],
       [False,  True]])

In [9]:
def bincount(a):
    n = a.max()+1
    a_off = a+(np.arange(a.shape[0])[:,None])*n
    M = a.shape[0]*n
    return (np.bincount(a_off.ravel(), minlength=M).reshape(-1,n)!=0).sum(1)


In [13]:
bincount(np.array([[1,2,5,6,6], [1,2,5,2,6]]))

array([4, 4])

In [14]:
def nunique_percol_bincount(a):
    n = a.max()+1
    a_off = a+(np.arange(a.shape[1]))*n
    M = a.shape[1]*n
    return (np.bincount(a_off.ravel(), minlength=M).reshape(-1,n)!=0).sum(1)


In [17]:
nunique_percol_bincount(np.array([[1,2,6,6,6], [1,3,5,3,6]]).T)

array([3, 4])