## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [5]:
np.ones(10)*2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [9]:
v = np.array([x for x in range(10)])
np.flip(v)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [12]:
m = np.arange(9)
np.reshape(m, [3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [17]:
a = np.array([1,2,0,0,4,0])
np.where(a!=0)[0].tolist()

[0, 1, 4]

Создать 3x3 единичную матрицу

In [22]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [25]:
np.random.rand(3,3)*10

array([[5.32119799, 5.94764332, 4.92910936],
       [0.87688362, 5.90408814, 6.2410104 ],
       [4.24255883, 2.30369992, 4.76836533]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [28]:
np.random.rand(30).mean()

0.47134591458336794

Перемножить матрицы 5x3 и 3x2

In [47]:
np.random.seed(5)
m1 = np.random.rand(5,3)
m2 = np.random.rand(3,2)
m1.dot(m2)

array([[0.43851527, 0.76348015],
       [0.75109979, 1.05463086],
       [0.53551429, 0.8213001 ],
       [0.50353332, 0.57154173],
       [0.67805002, 0.81024898]])

In [48]:
m1, m2

(array([[0.22199317, 0.87073231, 0.20671916],
        [0.91861091, 0.48841119, 0.61174386],
        [0.76590786, 0.51841799, 0.2968005 ],
        [0.18772123, 0.08074127, 0.7384403 ],
        [0.44130922, 0.15830987, 0.87993703]]),
 array([[0.27408646, 0.41423502],
        [0.29607993, 0.62878791],
        [0.57983781, 0.5999292 ]]))

In [49]:
0.22199317 * 0.27408646 + 0.87073231 * 0.29607993 + 0.20671916 * 0.57983781

0.4385152685224561

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [102]:
x = np.arange(0.05,1,0.1)
x

array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95])

Заменить максимальный элемент на ноль

In [60]:
x[x==x.max()]=0
x

array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.  ])

Преобразовать массив из float в int

In [62]:
x.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [185]:
ar = (np.random.rand(10,2)*10).astype(int)
ar

array([[8, 5],
       [0, 9],
       [3, 0],
       [8, 4],
       [8, 8],
       [3, 1],
       [8, 2],
       [0, 6],
       [0, 8],
       [7, 6]])

In [202]:
import scipy
lst = []
for x in ar:
    dist = scipy.spatial.distance.cdist(ar, [x])
    lst.append([x[0] for x in dist.tolist()])
np.array(lst)

array([[ 0.        ,  8.94427191,  7.07106781,  1.        ,  3.        ,
         6.40312424,  3.        ,  8.06225775,  8.54400375,  1.41421356],
       [ 8.94427191,  0.        ,  9.48683298,  9.43398113,  8.06225775,
         8.54400375, 10.63014581,  3.        ,  1.        ,  7.61577311],
       [ 7.07106781,  9.48683298,  0.        ,  6.40312424,  9.43398113,
         1.        ,  5.38516481,  6.70820393,  8.54400375,  7.21110255],
       [ 1.        ,  9.43398113,  6.40312424,  0.        ,  4.        ,
         5.83095189,  2.        ,  8.24621125,  8.94427191,  2.23606798],
       [ 3.        ,  8.06225775,  9.43398113,  4.        ,  0.        ,
         8.60232527,  6.        ,  8.24621125,  8.        ,  2.23606798],
       [ 6.40312424,  8.54400375,  1.        ,  5.83095189,  8.60232527,
         0.        ,  5.09901951,  5.83095189,  7.61577311,  6.40312424],
       [ 3.        , 10.63014581,  5.38516481,  2.        ,  6.        ,
         5.09901951,  0.        ,  8.94427191

Случайно расположить p элементов в 2D массив

In [175]:
p = 5
x, y = 10,10
ar = np.zeros(10*10)

In [176]:
ar[:5]=1
ar

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [178]:
np.random.shuffle(ar)
np.reshape(ar, [x,y])

array([[0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [103]:
x = np.arange(1, 6, 1)
x

array([1, 2, 3, 4, 5])

In [134]:
y = np.reshape(x, [5,1])
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [161]:
x1 = np.reshape(np.insert(y, (1,1,1),(0,0,0), axis=1), [1, 5*4])
x1

array([[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]])

In [170]:
np.delete(x1, np.s_[-3::])

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

Найти наиболее частое значение в массиве

In [82]:
np.random.seed(8)
x = (np.random.rand(200)*10).astype(int)

import scipy.stats as st

In [83]:
x

array([8, 9, 8, 5, 2, 0, 4, 4, 5, 4, 5, 5, 7, 7, 6, 4, 2, 9, 3, 2, 0, 9,
       1, 3, 0, 2, 3, 8, 3, 9, 0, 3, 3, 7, 9, 3, 4, 2, 8, 6, 0, 6, 7, 0,
       4, 7, 9, 5, 0, 4, 1, 6, 2, 1, 5, 1, 7, 9, 9, 3, 5, 6, 5, 4, 0, 0,
       4, 4, 1, 5, 5, 7, 3, 4, 8, 5, 7, 5, 8, 7, 8, 2, 2, 4, 4, 6, 8, 5,
       9, 7, 1, 6, 5, 7, 8, 2, 1, 6, 0, 7, 5, 9, 9, 2, 8, 8, 2, 6, 9, 7,
       0, 5, 4, 0, 9, 8, 2, 6, 4, 3, 5, 5, 8, 0, 6, 5, 1, 1, 6, 8, 0, 4,
       8, 4, 3, 2, 0, 1, 5, 5, 5, 2, 8, 8, 4, 7, 7, 3, 1, 2, 2, 3, 0, 2,
       5, 4, 5, 7, 9, 3, 2, 4, 6, 1, 0, 2, 2, 4, 6, 3, 9, 8, 6, 3, 1, 6,
       7, 0, 7, 8, 6, 7, 8, 9, 3, 0, 3, 1, 3, 5, 7, 9, 2, 9, 1, 4, 1, 2,
       0, 2])

In [84]:
st.mode(x)

ModeResult(mode=array([5]), count=array([25]))

In [85]:
dct = {}

In [88]:
for y in x:
    if y in dct:
        dct[y]+=1
    else:
        dct[y]=1
dct

{8: 60, 9: 54, 5: 75, 2: 69, 0: 60, 4: 66, 7: 60, 6: 51, 3: 57, 1: 48}

In [90]:
max(dct, key = lambda x: dct[x])

5

Найти n наибольших значений в массиве

In [91]:
np.random.seed(8)
x = (np.random.rand(200)*10).astype(int)
x

array([8, 9, 8, 5, 2, 0, 4, 4, 5, 4, 5, 5, 7, 7, 6, 4, 2, 9, 3, 2, 0, 9,
       1, 3, 0, 2, 3, 8, 3, 9, 0, 3, 3, 7, 9, 3, 4, 2, 8, 6, 0, 6, 7, 0,
       4, 7, 9, 5, 0, 4, 1, 6, 2, 1, 5, 1, 7, 9, 9, 3, 5, 6, 5, 4, 0, 0,
       4, 4, 1, 5, 5, 7, 3, 4, 8, 5, 7, 5, 8, 7, 8, 2, 2, 4, 4, 6, 8, 5,
       9, 7, 1, 6, 5, 7, 8, 2, 1, 6, 0, 7, 5, 9, 9, 2, 8, 8, 2, 6, 9, 7,
       0, 5, 4, 0, 9, 8, 2, 6, 4, 3, 5, 5, 8, 0, 6, 5, 1, 1, 6, 8, 0, 4,
       8, 4, 3, 2, 0, 1, 5, 5, 5, 2, 8, 8, 4, 7, 7, 3, 1, 2, 2, 3, 0, 2,
       5, 4, 5, 7, 9, 3, 2, 4, 6, 1, 0, 2, 2, 4, 6, 3, 9, 8, 6, 3, 1, 6,
       7, 0, 7, 8, 6, 7, 8, 9, 3, 0, 3, 1, 3, 5, 7, 9, 2, 9, 1, 4, 1, 2,
       0, 2])

In [95]:
n=5
np.sort(x)[-n:]

array([9, 9, 9, 9, 9])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [203]:
import pandas as pd

In [210]:
data = pd.read_csv('D:/python_my/ipynb/otus/1/en.openfoodfacts.org.products.tsv', sep='\t')

D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [211]:
data.head(5)

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [214]:
data.shape[0]

356027

Сколько столбцов в наборе данных?

In [215]:
data.shape[1]

163

Напечатайте все названия столбцов

In [217]:
data.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [218]:
data.columns[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [222]:
data.dtypes[105]

dtype('float64')

Как проиндексирован набор данных?

In [223]:
data.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [226]:
data['product_name'][19]

'Organic Oat Groats'

In [227]:
data.loc[19,'product_name']

'Organic Oat Groats'

In [228]:
data.at[19, 'product_name']

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?