## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [5]:
np.ones(10)*2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [9]:
v = np.array([x for x in range(10)])
np.flip(v)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [12]:
m = np.arange(9)
np.reshape(m, [3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [17]:
a = np.array([1,2,0,0,4,0])
np.where(a!=0)[0].tolist()

[0, 1, 4]

Создать 3x3 единичную матрицу

In [22]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [25]:
np.random.rand(3,3)*10

array([[5.32119799, 5.94764332, 4.92910936],
       [0.87688362, 5.90408814, 6.2410104 ],
       [4.24255883, 2.30369992, 4.76836533]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [28]:
np.random.rand(30).mean()

0.47134591458336794

Перемножить матрицы 5x3 и 3x2

In [47]:
np.random.seed(5)
m1 = np.random.rand(5,3)
m2 = np.random.rand(3,2)
m1.dot(m2)

array([[0.43851527, 0.76348015],
       [0.75109979, 1.05463086],
       [0.53551429, 0.8213001 ],
       [0.50353332, 0.57154173],
       [0.67805002, 0.81024898]])

In [48]:
m1, m2

(array([[0.22199317, 0.87073231, 0.20671916],
        [0.91861091, 0.48841119, 0.61174386],
        [0.76590786, 0.51841799, 0.2968005 ],
        [0.18772123, 0.08074127, 0.7384403 ],
        [0.44130922, 0.15830987, 0.87993703]]),
 array([[0.27408646, 0.41423502],
        [0.29607993, 0.62878791],
        [0.57983781, 0.5999292 ]]))

In [49]:
0.22199317 * 0.27408646 + 0.87073231 * 0.29607993 + 0.20671916 * 0.57983781

0.4385152685224561

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [102]:
x = np.arange(0.05,1,0.1)
x

array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95])

Заменить максимальный элемент на ноль

In [60]:
x[x==x.max()]=0
x

array([0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.  ])

Преобразовать массив из float в int

In [62]:
x.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [185]:
ar = (np.random.rand(10,2)*10).astype(int)
ar

array([[8, 5],
       [0, 9],
       [3, 0],
       [8, 4],
       [8, 8],
       [3, 1],
       [8, 2],
       [0, 6],
       [0, 8],
       [7, 6]])

In [202]:
import scipy
lst = []
for x in ar:
    dist = scipy.spatial.distance.cdist(ar, [x])
    lst.append([x[0] for x in dist.tolist()])
np.array(lst)

array([[ 0.        ,  8.94427191,  7.07106781,  1.        ,  3.        ,
         6.40312424,  3.        ,  8.06225775,  8.54400375,  1.41421356],
       [ 8.94427191,  0.        ,  9.48683298,  9.43398113,  8.06225775,
         8.54400375, 10.63014581,  3.        ,  1.        ,  7.61577311],
       [ 7.07106781,  9.48683298,  0.        ,  6.40312424,  9.43398113,
         1.        ,  5.38516481,  6.70820393,  8.54400375,  7.21110255],
       [ 1.        ,  9.43398113,  6.40312424,  0.        ,  4.        ,
         5.83095189,  2.        ,  8.24621125,  8.94427191,  2.23606798],
       [ 3.        ,  8.06225775,  9.43398113,  4.        ,  0.        ,
         8.60232527,  6.        ,  8.24621125,  8.        ,  2.23606798],
       [ 6.40312424,  8.54400375,  1.        ,  5.83095189,  8.60232527,
         0.        ,  5.09901951,  5.83095189,  7.61577311,  6.40312424],
       [ 3.        , 10.63014581,  5.38516481,  2.        ,  6.        ,
         5.09901951,  0.        ,  8.94427191

Случайно расположить p элементов в 2D массив

In [175]:
p = 5
x, y = 10,10
ar = np.zeros(10*10)

In [176]:
ar[:5]=1
ar

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [178]:
np.random.shuffle(ar)
np.reshape(ar, [x,y])

array([[0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [103]:
x = np.arange(1, 6, 1)
x

array([1, 2, 3, 4, 5])

In [134]:
y = np.reshape(x, [5,1])
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [161]:
x1 = np.reshape(np.insert(y, (1,1,1),(0,0,0), axis=1), [1, 5*4])
x1

array([[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]])

In [170]:
np.delete(x1, np.s_[-3::])

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

Найти наиболее частое значение в массиве

In [82]:
np.random.seed(8)
x = (np.random.rand(200)*10).astype(int)

import scipy.stats as st

In [83]:
x

array([8, 9, 8, 5, 2, 0, 4, 4, 5, 4, 5, 5, 7, 7, 6, 4, 2, 9, 3, 2, 0, 9,
       1, 3, 0, 2, 3, 8, 3, 9, 0, 3, 3, 7, 9, 3, 4, 2, 8, 6, 0, 6, 7, 0,
       4, 7, 9, 5, 0, 4, 1, 6, 2, 1, 5, 1, 7, 9, 9, 3, 5, 6, 5, 4, 0, 0,
       4, 4, 1, 5, 5, 7, 3, 4, 8, 5, 7, 5, 8, 7, 8, 2, 2, 4, 4, 6, 8, 5,
       9, 7, 1, 6, 5, 7, 8, 2, 1, 6, 0, 7, 5, 9, 9, 2, 8, 8, 2, 6, 9, 7,
       0, 5, 4, 0, 9, 8, 2, 6, 4, 3, 5, 5, 8, 0, 6, 5, 1, 1, 6, 8, 0, 4,
       8, 4, 3, 2, 0, 1, 5, 5, 5, 2, 8, 8, 4, 7, 7, 3, 1, 2, 2, 3, 0, 2,
       5, 4, 5, 7, 9, 3, 2, 4, 6, 1, 0, 2, 2, 4, 6, 3, 9, 8, 6, 3, 1, 6,
       7, 0, 7, 8, 6, 7, 8, 9, 3, 0, 3, 1, 3, 5, 7, 9, 2, 9, 1, 4, 1, 2,
       0, 2])

In [84]:
st.mode(x)

ModeResult(mode=array([5]), count=array([25]))

In [85]:
dct = {}

In [88]:
for y in x:
    if y in dct:
        dct[y]+=1
    else:
        dct[y]=1
dct

{8: 60, 9: 54, 5: 75, 2: 69, 0: 60, 4: 66, 7: 60, 6: 51, 3: 57, 1: 48}

In [90]:
max(dct, key = lambda x: dct[x])

5

Найти n наибольших значений в массиве

In [91]:
np.random.seed(8)
x = (np.random.rand(200)*10).astype(int)
x

array([8, 9, 8, 5, 2, 0, 4, 4, 5, 4, 5, 5, 7, 7, 6, 4, 2, 9, 3, 2, 0, 9,
       1, 3, 0, 2, 3, 8, 3, 9, 0, 3, 3, 7, 9, 3, 4, 2, 8, 6, 0, 6, 7, 0,
       4, 7, 9, 5, 0, 4, 1, 6, 2, 1, 5, 1, 7, 9, 9, 3, 5, 6, 5, 4, 0, 0,
       4, 4, 1, 5, 5, 7, 3, 4, 8, 5, 7, 5, 8, 7, 8, 2, 2, 4, 4, 6, 8, 5,
       9, 7, 1, 6, 5, 7, 8, 2, 1, 6, 0, 7, 5, 9, 9, 2, 8, 8, 2, 6, 9, 7,
       0, 5, 4, 0, 9, 8, 2, 6, 4, 3, 5, 5, 8, 0, 6, 5, 1, 1, 6, 8, 0, 4,
       8, 4, 3, 2, 0, 1, 5, 5, 5, 2, 8, 8, 4, 7, 7, 3, 1, 2, 2, 3, 0, 2,
       5, 4, 5, 7, 9, 3, 2, 4, 6, 1, 0, 2, 2, 4, 6, 3, 9, 8, 6, 3, 1, 6,
       7, 0, 7, 8, 6, 7, 8, 9, 3, 0, 3, 1, 3, 5, 7, 9, 2, 9, 1, 4, 1, 2,
       0, 2])

In [95]:
n=5
np.sort(x)[-n:]

array([9, 9, 9, 9, 9])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [203]:
import pandas as pd

In [210]:
data = pd.read_csv('D:/python_my/ipynb/otus/1/en.openfoodfacts.org.products.tsv', sep='\t')

D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [211]:
data.head(5)

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [214]:
data.shape[0]

356027

Сколько столбцов в наборе данных?

In [215]:
data.shape[1]

163

Напечатайте все названия столбцов

In [217]:
data.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [218]:
data.columns[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [222]:
data.dtypes[105]

dtype('float64')

Как проиндексирован набор данных?

In [223]:
data.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [226]:
data['product_name'][19]

'Organic Oat Groats'

In [227]:
data.loc[19,'product_name']

'Organic Oat Groats'

In [228]:
data.at[19, 'product_name']

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [3]:
import pandas as pd
ds = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

In [7]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB


In [51]:
ds.describe()

order_id     quantity        price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [8]:
ds.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [17]:
ds['price']=ds['item_price'].str.replace('\\$', '').astype(float)

In [19]:
ds['price'].head()

0     2.39
1     3.39
2     3.39
3     2.39
4    16.98
Name: price, dtype: float64

In [20]:
ds['price'].isnull().sum()

0

In [23]:
ds[ds['price']>10].shape[0]

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [25]:
ds[['item_name','item_price']].head(10)

item_name item_price
0           Chips and Fresh Tomato Salsa     $2.39 
1                                   Izze     $3.39 
2                       Nantucket Nectar     $3.39 
3  Chips and Tomatillo-Green Chili Salsa     $2.39 
4                           Chicken Bowl    $16.98 
5                           Chicken Bowl    $10.98 
6                          Side of Chips     $1.69 
7                          Steak Burrito    $11.75 
8                       Steak Soft Tacos     $9.25 
9                          Steak Burrito     $9.25

Отсортировать по имени предмета

In [55]:
ds.sort_values(by='item_name')[::100]

order_id  quantity                            item_name  \
3389      1360         2                    6 Pack Soft Drink   
219         97         1                        Barbacoa Bowl   
3149      1256         1                     Barbacoa Burrito   
2799      1112         1                        Bottled Water   
2700      1071         1                        Bottled Water   
1662       672         1                          Canned Soda   
3186      1274         1                    Canned Soft Drink   
3210      1283         1                    Canned Soft Drink   
4552      1809         1                    Canned Soft Drink   
1097       452         1                     Carnitas Burrito   
2080       839         1                  Carnitas Soft Tacos   
1474       599         1                         Chicken Bowl   
3214      1285         1                         Chicken Bowl   
2282       916         1                         Chicken Bowl   
2070       835         1                         Chicken Bowl   
837        345         1                         Chicken Bowl   
654        271         2                         Chicken Bowl   
4087      1637         1                         Chicken Bowl   
3961      1587         1                      Chicken Burrito   
3256      1304         1                      Chicken Burrito   
1616       653         1                      Chicken Burrito   
1398       569         1                      Chicken Burrito   
4222      1685         1                      Chicken Burrito   
600        247         1                 Chicken Crispy Tacos   
1977       798         1                   Chicken Salad Bowl   
4118      1649         1                   Chicken Soft Tacos   
3263      1306         1                                Chips   
1546       628         1                                Chips   
3407      1367         1         Chips and Fresh Tomato Salsa   
1990       804         1                  Chips and Guacamole   
3241      1298         1                  Chips and Guacamole   
1881       759         2                  Chips and Guacamole   
2890      1149         1                  Chips and Guacamole   
20          10         1                  Chips and Guacamole   
1628       656         1   Chips and Roasted Chili-Corn Salsa   
1915       773         1  Chips and Tomatillo Red Chili Salsa   
2430       965         1                     Nantucket Nectar   
525        219         1                        Side of Chips   
3144      1254         1                           Steak Bowl   
1890       763         1                           Steak Bowl   
4117      1649         1                        Steak Burrito   
2328       927         1                        Steak Burrito   
1139       471         1                        Steak Burrito   
3778      1512         1                   Steak Crispy Tacos   
4052      1622         1                     Steak Soft Tacos   
2685      1067         1                       Veggie Burrito   
3223      1289         1                    Veggie Salad Bowl   

                                     choice_description item_price  price  
3389                                        [Diet Coke]    $12.98   12.98  
219   [Tomatillo Red Chili Salsa, [Rice, Black Beans...     $9.25    9.25  
3149  [Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...     $8.99    8.99  
2799                                                NaN     $1.50    1.50  
2700                                                NaN     $1.50    1.50  
1662                                        [Diet Coke]     $1.09    1.09  
3186                                             [Coke]     $1.25    1.25  
3210                                        [Diet Coke]     $1.25    1.25  
4552                                           [Sprite]     $1.25    1.25  
1097  [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...    $11.75   11.75  
2080                      [Tomatillo Green Chili 

Сколько было заказано самого дорогого предмета?

In [30]:
m = ds['price'].max()

In [35]:
ds.loc[ds['price']==m, ['quantity', 'item_name']]

quantity                     item_name
3598        15  Chips and Fresh Tomato Salsa

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [38]:
ds.loc[ds['item_name']=='Veggie Salad Bowl', ['quantity']].sum()

quantity    18
dtype: int64

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [49]:
test = ds.loc[(ds['item_name']=='Canned Soda') & (ds['quantity']>1)]
test

order_id  quantity    item_name choice_description item_price  price
18           9         2  Canned Soda           [Sprite]     $2.18    2.18
51          23         2  Canned Soda     [Mountain Dew]     $2.18    2.18
162         73         2  Canned Soda        [Diet Coke]     $2.18    2.18
171         76         2  Canned Soda  [Diet Dr. Pepper]     $2.18    2.18
350        150         2  Canned Soda        [Diet Coke]     $2.18    2.18
352        151         2  Canned Soda        [Coca Cola]     $2.18    2.18
698        287         2  Canned Soda        [Coca Cola]     $2.18    2.18
700        288         2  Canned Soda        [Coca Cola]     $2.18    2.18
909        376         2  Canned Soda     [Mountain Dew]     $2.18    2.18
1091       450         2  Canned Soda       [Dr. Pepper]     $2.18    2.18
1092       450         2  Canned Soda        [Coca Cola]     $2.18    2.18
1944       787         2  Canned Soda       [Dr. Pepper]     $2.18    2.18
2135       859         2  Canned Soda        [Diet Coke]     $2.18    2.18
2235       901         4  Canned Soda           [Sprite]     $4.36    4.36
2905      1156         2  Canned Soda        [Coca Cola]     $2.18    2.18
2906      1156         2  Canned Soda           [Sprite]     $2.18    2.18
3152      1258         2  Canned Soda       [Dr. Pepper]     $2.18    2.18
3364      1349         2  Canned Soda        [Coca Cola]     $2.18    2.18
3592      1440         2  Canned Soda        [Diet Coke]     $2.18    2.18
3866      1550         2  Canned Soda     [Mountain Dew]     $2.18    2.18

In [54]:
len(test.index)

20